package main

// Math plugin
// compiling the plugin:
// go build -buildmode=plugin -o math.so
// buildmode=plugin suggests the Go compiler to compile the code in plugin mode (not as binary package)
// math.so is the "shared library"/"plugin" generated by the go compiler. Can be stored anywhere

import (
	"fmt"
	"io/ioutil"
)

func Put(key string, value []byte) error {
	fmt.Println("\nCall for Put")
	return ioutil.WriteFile("kv_"+key, value, 0644)
}

func Get(key string) (value []byte, err error) {
	fmt.Println("\nCall for Get")
	val, err := ioutil.ReadFile("kv_" + key)
	if err != nil {
		return nil, err
	}
	return val, nil
}
